---

- name: checksum
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: get checksum list
      bodsch.scm.github_checksum:
        project: superseriousbusiness
        repository: gotosocial
        checksum_file: "{{ __gotosocial_files.checksum }}"
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        architecture: "{{ ansible_architecture }}"
        system: "{{ ansible_facts.system }}"
        version: "v{{ gotosocial_version }}"
      register: _latest_checksum

    - name: define checksum for {{ go_arch }} architecture
      ansible.builtin.set_fact:
        __gotosocial_checksum: "{{ _latest_checksum.checksum }}"
      when:
        - _latest_checksum.rc == 0
        - _latest_checksum.checksum is defined
        - _latest_checksum.checksum | string | length > 0

    - name: define checksum for web-assets
      ansible.builtin.set_fact:
        __gotosocial_assets_checksum: "{{ _latest_checksum.checksums | gotosocial_assets_checksum() }}"
      when:
        - _latest_checksum.rc == 0
        - _latest_checksum.checksums is defined
        - _latest_checksum.checksums | count > 0

- name: download gotosocial binary archive
  become: false
  delegate_to: "{{ gotosocial_delegate_to }}"
  ansible.builtin.get_url:
    url: "{{ gotosocial_release_download_url }}/download/v{{ gotosocial_version }}/{{ __gotosocial_files.archive }}"
    dest: "{{ gotosocial_local_tmp_directory }}/"
    checksum: "sha256:{{ __gotosocial_checksum }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: download web-assets archive
  become: false
  delegate_to: "{{ gotosocial_delegate_to }}"
  ansible.builtin.get_url:
    url: "{{ gotosocial_release_download_url }}/download/v{{ gotosocial_version }}/{{ __gotosocial_files.assets }}"
    dest: "{{ gotosocial_local_tmp_directory }}/"
    checksum: "sha256:{{ __gotosocial_assets_checksum }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract gotosocial archive
  become: false
  delegate_to: "{{ gotosocial_delegate_to }}"
  run_once: "{{ 'false' if gotosocial_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ gotosocial_local_tmp_directory }}/{{ __gotosocial_files.binary }}"
    dest: "{{ gotosocial_local_tmp_directory }}"
    copy: false
  register: _extract_archive

...
