---

- name: detect binary file for gotosocial on {{ gotosocial_delegate_to }}
  become: false
  delegate_to: "{{ gotosocial_delegate_to }}"
  ansible.builtin.stat:
    path: "{{ gotosocial_local_tmp_directory }}/gotosocial"
  register: stat_file_binary

- name: propagate gotosocial binaries
  ansible.builtin.copy:
    src: "{{ gotosocial_local_tmp_directory }}/gotosocial"
    dest: "{{ gotosocial_install_path }}/gotosocial"
    mode: 0755
    owner: "{{ gotosocial_system_user }}"
    group: "{{ gotosocial_system_group }}"
    remote_src: "{{ 'true' if gotosocial_direct_download else 'false' }}"
  when:
    - stat_file_binary.stat.exists

- name: propagate gotosocial asset
  ansible.builtin.copy:
    src: "{{ gotosocial_local_tmp_directory }}/{{ __gotosocial_files.assets }}"
    dest: "{{ gotosocial_data_dir }}/"
    mode: 0755
    owner: "{{ gotosocial_system_user }}"
    group: "{{ gotosocial_system_group }}"
    remote_src: "{{ 'true' if gotosocial_direct_download else 'false' }}"
  when:
    - stat_file_binary.stat.exists

- name: extract web-assets archive
  ansible.builtin.unarchive:
    src: "{{ gotosocial_data_dir }}/{{ __gotosocial_files.assets }}"
    dest: "{{ gotosocial_install_path }}/"
    copy: false
  register: _extract_archive

- name: make files executable
  ansible.builtin.file:
    path: "{{ gotosocial_install_path }}/gotosocial"
    mode: 0755
    owner: "{{ gotosocial_system_user }}"
    group: "{{ gotosocial_system_group }}"

- name: create custom fact file
  bodsch.core.facts:
    name: gotosocial
    facts:
      version: "{{ gotosocial_version }}"

- name: create gotosocial data directory
  ansible.builtin.file:
    state: directory
    path: "{{ gotosocial_data_dir }}"
    mode: 0750
    owner: "{{ gotosocial_system_user }}"
    group: "{{ gotosocial_system_group }}"

- name: create link to binary
  ansible.builtin.file:
    src: "{{ gotosocial_install_path }}/gotosocial"
    dest: "/usr/bin/gotosocial"
    state: link
    force: true
    follow: false
  notify:
    - restart gotosocial

- name: create gotosocial local storage directory
  ansible.builtin.file:
    path: "{{ gotosocial_config.storage.local_base_path }}"
    state: directory
    owner: "{{ gotosocial_system_user }}"
    group: "{{ gotosocial_system_group }}"
    mode: 0755

- name: create link to assets
  ansible.builtin.file:
    src: "{{ gotosocial_install_path }}/web"
    dest: "{{ gotosocial_data_dir }}/web"
    state: link
    force: true
    follow: false
  notify:
    - restart gotosocial

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/gotosocial.service.j2"
        dest: "{{ systemd_lib_directory }}/gotosocial.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart gotosocial

    - name: create systemd service configuration
      ansible.builtin.template:
        src: "gotosocial.j2"
        dest: "{{ gotosocial_defaults_directory }}/gotosocial"
        force: true
        owner: root
        group: "{{ gotosocial_system_group }}"
        mode: 0640
      notify:
        - validate config
        - reload gotosocial

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/gotosocial.j2"
        dest: "/etc/conf.d/gotosocial"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init file
      ansible.builtin.template:
        src: "init/openrc/init.d/gotosocial.j2"
        dest: "/etc/init.d/gotosocial"
        owner: root
        group: root
        mode: 0750

...
