---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yaml
      skip: true


- name: install dependency
  ansible.builtin.package:
    name: "{{ gotosocial_requirements }}"
    state: present
  when:
    - gotosocial_requirements | default([]) | count > 0


- name: merge gotosocial configuration between defaults and custom
  ansible.builtin.set_fact:
    gotosocial_service: "{{ gotosocial_defaults_service | combine(gotosocial_service, recursive=True) }}"
    gotosocial_config: "{{ gotosocial_defaults_config | combine(gotosocial_config, recursive=True) }}"

- name: define gotosocial data directory
  ansible.builtin.set_fact:
    gotosocial_data_dir: "{{ gotosocial_storage.filesystem.rootdirectory | default('/var/lib/gotosocial') }}"

...
