---

nginx_events:
  multi_accept: true

nginx_gzip:
  enabled: true

nginx_logformat:
  json_combined:
    format: |
      '{'
        '"time_local": "$time_local",'
        '"remote_addr": "$remote_addr",'
        '"remote_user": "$remote_user",'
        '"request": "$request",'
        '"status": "$status",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"request_time": "$request_time",'
        '"http_referrer": "$http_referer",'
        '"http_user_agent": "$http_user_agent"'
      '}';
    # escape: json

# The client_max_body_size parameter is now set to 16384m, making the maximum upload size equal to 16GB.
nginx_http:
  rewrite_log: true
  client_max_body_size: 16384m

nginx_vhosts:
  social:
    filename: 00-social.conf
    state: present  # default: present
    enabled: true   # default: true

    domains:
      - social.molecule.lan
      - molecule.molecule.lan

    # creates also an HTTP vhost only for redirect to HTTPS
    #redirect:
    #  from_port: 80

    listen:
      - "80"
      # - "443 ssl http2"

    upstreams:
      - name: gotosocial
        servers:
          - 127.0.0.1:8080

    logfiles:
      access:
        file: /var/log/nginx/social.molecule.lan/access.log
        # loglevel: json_combined
      error:
        file: /var/log/nginx/social.molecule.lan/error.log
        loglevel: notice

    # # enable ssl
    # ssl:
    #   enabled: false
    #   certificate: /etc/snakeoil/matrix.lan/matrix.lan.crt
    #   certificate_key: /etc/snakeoil/matrix.lan/matrix.lan.key
    #   dhparam: /etc/snakeoil/matrix.lan/dh.pem

    locations:
      "/":
        options: |
          add_header X-Backend "social";

          proxy_pass                            http://gotosocial;
          proxy_set_header    Host              $host;
          proxy_set_header    X-Real-IP         $remote_addr;
          proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Proto $scheme;
