---

- name: restart gotosocial
  become: true
  ansible.builtin.service:
    name: gotosocial
    state: restarted

- name: reload gotosocial
  become: true
  ansible.builtin.service:
    name: gotosocial
    state: reloaded

- name: validate config
  ansible.builtin.command: /bin/true

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
